### ISSUE TITLE
Test "n-th Percentile Response Time" not working as expected

### ISSUE THREAD

**Issue by alex-fournier** [deliverymind/lightning#53]
This is taken from my test result:

```
Test type: nthPercRespTimeTest
Transaction name: list-messages
Expected result: 90th percentile of transactions have response time <= 1000
Actual result: 90th percentile of transactions have response time = 1301
Transaction count: 10
Longest transactions: [1438, 75, 67, 61, 59]
Test result: FAIL
```

With 10 transactions and a percentile of 90, I was hoping that the longest transaction would be ignored.
I use this type of test to exclude rare unexpected long transactions, which I consider as "accident" and not really as a problem.
I have other tests to ensure a maximum response time.
Regarding how JMeter determines its 90% centile and what I was expecting, we should rather have something like:

```
Test type: nthPercRespTimeTest
Transaction name: list-messages
Expected result: 90th percentile of transactions have response time <= 1000
Actual result: 90th percentile of transactions have response time = 75
Transaction count: 10
Longest transactions: [1438, 75, 67, 61, 59]
Test result: PASS
```

I started working on it and I found a quick and clean fix, PR incoming shortly...

**Comment by automatictester** [comment]
As you correctly pointed out, there are multiple ways to calculate. However, your code makes it consistent with JMeter. I'll merge it in, and raise a ticket for future to make this configurable - just in case.

**Comment by alex-fournier** [comment]
Thanks for the merge, a release would be perfect!

**Comment by automatictester** [comment]
Artefacts have been released. It should be available in Central in 10 mins and searchable via Central's web interface in 2 hours. However, recently Central had massive delays in both syncing artefacts and updating indices for search functionality. Artefacts should be ready to use when you can see them [here](https://repo1.maven.org/maven2/uk/co/deliverymind/). Even, if you can't see them [here](http://search.maven.org/#search|ga|1|g%3A%22uk.co.deliverymind%22).

**Comment by alex-fournier** [comment]
Thank you :)
