### ISSUE TITLE
Throughput test converts double to int

### ISSUE THREAD

**Issue by burtoni** [deliverymind/lightning#63]
The test spec for throughput (http://deliverymind.github.io/lightning/test_types.html) specifies that minThroughput accepts double numbers.

Internally, it looks like it converts that number to an int before comparing it against the actual throughput; as a result, specifying a throughput less than 1 (e.g. 0.95) gets compared against a number that loses precision (and is reported as 0):

```
Test name:            My Service - transaction rate
    Test type:            throughputTest
    Test description:     Transaction rate for the /testme endpoint
    Transaction name:     testme
    Expected result:      Throughput >= 0.95 / second
    Actual result:        Throughput = 0 / second 
```
The relevant code in ThroughputTest.java gets the actual throughput as an int before comparing it against the double minThroughput:
`actualResult = (int) transactions.getThroughput();`

If the test allows double values to be specified, it should report/compare on a double value.

**Comment by automatictester** [comment]
actualResult should not be an int, it should be a double. When displayed, should be in same format as expected result. It should be a minor fix. Can you provide a pull request?

**Comment by burtoni** [comment]
Should be doable, let me have a dig
