### ISSUE TITLE
Test type on HTTP response code

### ISSUE THREAD

**Issue by burtoni** [deliverymind/lightning#64]
It would be useful to distinguish between HTTP codes as a test type.

Currently all 404s and 500s are treated as a failure by JMeter, but in some REST applications, a 404 might be an "expected" request. A Passed Transactions test is unable to distinguish these.

(This is a feature request)

Alternatives in JMeter configuration:
* User could add a Response Assertion to allow 404 to not be an error

**Comment by burtoni** [comment]
See http://stackoverflow.com/questions/36824822/teamcity-jmeter-performance-metrics-calculation-check-reference-values

**Comment by automatictester** [comment]
Passed transactions test considers an error whatever JMeter considered to be an error. If your JMeter test considers 404 to be success, it will be reported as success in CSV file and subsequently processed by Lightning. I don't see a reason why Lightning should re-evaluate what JMeter considers to be success.
