### ISSUE TITLE
Is there anyway i can pass csv and xml file paths in gradle verify task? 

### ISSUE THREAD

**Issue by msrraju13** [deliverymind/lightning#69]

**Comment by msrraju13** [comment]
Help Needed

**Comment by automatictester** [comment]
Hi @msrraju13 I think you can find answer to your question on the [Lightning website](http://deliverymind.github.io/lightning/gradle_plugin.html) and more specifically in [usage example](https://github.com/deliverymind/lightning-gradle-plugin-example/blob/master/build.gradle).

**Comment by msrraju13** [comment]
got it, thank you very much, is there any ideas for both run test and verify?

**Comment by automatictester** [comment]
Not sure what you mean by _run test_. If you are asking about the report mode, you can find it in report mode [docs](http://deliverymind.github.io/lightning/report_mode.html).

**Comment by msrraju13** [comment]
No...I am asking for feasibility to run Jmeter Tests and verify results using this plugin

**Comment by automatictester** [comment]
Purpose of this project is to analyse results produced by JMeter. How you run JMeter itself, is out of scope for Lightning.
